// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddConfig'](arg1, arg2, arg3);
}

export function EnableConfig(arg1, arg2) {
  return window['go']['main']['App']['EnableConfig'](arg1, arg2);
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function RegisterSIP() {
  return window['go']['main']['App']['RegisterSIP']();
}

export function RemoveConfig(arg1, arg2) {
  return window['go']['main']['App']['RemoveConfig'](arg1, arg2);
}
