// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Answer(arg1) {
  return window['go']['app']['App']['Answer'](arg1);
}

export function AttendedTransfer(arg1, arg2) {
  return window['go']['app']['App']['AttendedTransfer'](arg1, arg2);
}

export function AudioDevices() {
  return window['go']['app']['App']['AudioDevices']();
}

export function CSVColumns(arg1) {
  return window['go']['app']['App']['CSVColumns'](arg1);
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function ClearMessages() {
  return window['go']['app']['App']['ClearMessages']();
}

export function Conference(arg1) {
  return window['go']['app']['App']['Conference'](arg1);
}

export function ConfigureGlobalShortcuts() {
  return window['go']['app']['App']['ConfigureGlobalShortcuts']();
}

export function Contacts(arg1) {
  return window['go']['app']['App']['Contacts'](arg1);
}

export function ContactsPage(arg1, arg2, arg3) {
  return window['go']['app']['App']['ContactsPage'](arg1, arg2, arg3);
}

export function Conversations(arg1, arg2) {
  return window['go']['app']['App']['Conversations'](arg1, arg2);
}

export function DeleteContact(arg1) {
  return window['go']['app']['App']['DeleteContact'](arg1);
}

export function DeleteConversation(arg1, arg2) {
  return window['go']['app']['App']['DeleteConversation'](arg1, arg2);
}

export function DeleteDirectoryPassword() {
  return window['go']['app']['App']['DeleteDirectoryPassword']();
}

export function DeleteHistory(arg1) {
  return window['go']['app']['App']['DeleteHistory'](arg1);
}

export function DeleteSavedPassword(arg1) {
  return window['go']['app']['App']['DeleteSavedPassword'](arg1);
}

export function DesktopSettings() {
  return window['go']['app']['App']['DesktopSettings']();
}

export function Dial(arg1, arg2) {
  return window['go']['app']['App']['Dial'](arg1, arg2);
}

export function DialFeature(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DialFeature'](arg1, arg2, arg3, arg4);
}

export function DialVoicemail(arg1) {
  return window['go']['app']['App']['DialVoicemail'](arg1);
}

export function DirectoryState() {
  return window['go']['app']['App']['DirectoryState']();
}

export function DisableConfig(arg1) {
  return window['go']['app']['App']['DisableConfig'](arg1);
}

export function DisableGlobalShortcuts() {
  return window['go']['app']['App']['DisableGlobalShortcuts']();
}

export function DiscoverDirectory(arg1) {
  return window['go']['app']['App']['DiscoverDirectory'](arg1);
}

export function DiscoverDirectoryServers(arg1) {
  return window['go']['app']['App']['DiscoverDirectoryServers'](arg1);
}

export function EnableConfig(arg1, arg2) {
  return window['go']['app']['App']['EnableConfig'](arg1, arg2);
}

export function EnableGlobalShortcuts() {
  return window['go']['app']['App']['EnableGlobalShortcuts']();
}

export function ExportContacts(arg1) {
  return window['go']['app']['App']['ExportContacts'](arg1);
}

export function ExportContactsCSV() {
  return window['go']['app']['App']['ExportContactsCSV']();
}

export function ExportContactsVCard() {
  return window['go']['app']['App']['ExportContactsVCard']();
}

export function ExportDiagnostics(arg1) {
  return window['go']['app']['App']['ExportDiagnostics'](arg1);
}

export function GetConfig(arg1, arg2) {
  return window['go']['app']['App']['GetConfig'](arg1, arg2);
}

export function GetGlobalShortcuts() {
  return window['go']['app']['App']['GetGlobalShortcuts']();
}

export function Hangup(arg1) {
  return window['go']['app']['App']['Hangup'](arg1);
}

export function History() {
  return window['go']['app']['App']['History']();
}

export function HistoryPage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['HistoryPage'](arg1, arg2, arg3, arg4);
}

export function Hold(arg1, arg2) {
  return window['go']['app']['App']['Hold'](arg1, arg2);
}

export function ImportContactFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportContactFile'](arg1, arg2, arg3);
}

export function ImportContactsCSV(arg1) {
  return window['go']['app']['App']['ImportContactsCSV'](arg1);
}

export function ImportContactsVCard(arg1) {
  return window['go']['app']['App']['ImportContactsVCard'](arg1);
}

export function ImportDirectory(arg1) {
  return window['go']['app']['App']['ImportDirectory'](arg1);
}

export function LastDialed(arg1) {
  return window['go']['app']['App']['LastDialed'](arg1);
}

export function LeaveConference() {
  return window['go']['app']['App']['LeaveConference']();
}

export function ListConfigs() {
  return window['go']['app']['App']['ListConfigs']();
}

export function LookupDirectory(arg1) {
  return window['go']['app']['App']['LookupDirectory'](arg1);
}

export function MapContactCSV(arg1, arg2) {
  return window['go']['app']['App']['MapContactCSV'](arg1, arg2);
}

export function MarkConversationRead(arg1, arg2, arg3) {
  return window['go']['app']['App']['MarkConversationRead'](arg1, arg2, arg3);
}

export function Messages(arg1, arg2) {
  return window['go']['app']['App']['Messages'](arg1, arg2);
}

export function MessagesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['MessagesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function Mute(arg1, arg2) {
  return window['go']['app']['App']['Mute'](arg1, arg2);
}

export function PreviewContactImport(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewContactImport'](arg1, arg2, arg3);
}

export function PublishStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['PublishStatus'](arg1, arg2, arg3);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function Redirect(arg1, arg2) {
  return window['go']['app']['App']['Redirect'](arg1, arg2);
}

export function RefreshDirectory() {
  return window['go']['app']['App']['RefreshDirectory']();
}

export function RemoveConfig(arg1, arg2) {
  return window['go']['app']['App']['RemoveConfig'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['app']['App']['RequestQuit']();
}

export function RestartMediaPath(arg1) {
  return window['go']['app']['App']['RestartMediaPath'](arg1);
}

export function RestoreDirectoryContact(arg1) {
  return window['go']['app']['App']['RestoreDirectoryContact'](arg1);
}

export function RetryAudio(arg1) {
  return window['go']['app']['App']['RetryAudio'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['app']['App']['SaveContact'](arg1);
}

export function SaveDirectoryProfile(arg1, arg2) {
  return window['go']['app']['App']['SaveDirectoryProfile'](arg1, arg2);
}

export function SendDTMF(arg1, arg2) {
  return window['go']['app']['App']['SendDTMF'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetAudio(arg1) {
  return window['go']['app']['App']['SetAudio'](arg1);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetConfig'](arg1, arg2, arg3);
}

export function SetDND(arg1) {
  return window['go']['app']['App']['SetDND'](arg1);
}

export function SetGain(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetGain'](arg1, arg2, arg3);
}

export function SetPreferences(arg1) {
  return window['go']['app']['App']['SetPreferences'](arg1);
}

export function Snapshot() {
  return window['go']['app']['App']['Snapshot']();
}

export function StartRecording(arg1) {
  return window['go']['app']['App']['StartRecording'](arg1);
}

export function StopRecording(arg1) {
  return window['go']['app']['App']['StopRecording'](arg1);
}

export function TakeDialTarget() {
  return window['go']['app']['App']['TakeDialTarget']();
}

export function TestAudio(arg1, arg2) {
  return window['go']['app']['App']['TestAudio'](arg1, arg2);
}

export function Transfer(arg1, arg2) {
  return window['go']['app']['App']['Transfer'](arg1, arg2);
}

export function UnpublishStatus(arg1) {
  return window['go']['app']['App']['UnpublishStatus'](arg1);
}

export function UnwatchPresence(arg1, arg2) {
  return window['go']['app']['App']['UnwatchPresence'](arg1, arg2);
}

export function WatchPresence(arg1, arg2) {
  return window['go']['app']['App']['WatchPresence'](arg1, arg2);
}

export function WatchVoicemail(arg1) {
  return window['go']['app']['App']['WatchVoicemail'](arg1);
}
