// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {store} from '../models';
import {app} from '../models';
import {directory} from '../models';
import {config} from '../models';
import {desktop} from '../models';
import {media} from '../models';
import {phone} from '../models';

export function Answer(arg1:string):Promise<void>;

export function AttendedTransfer(arg1:string,arg2:string):Promise<void>;

export function AudioDevices():Promise<Array<audio.Device>>;

export function CSVColumns(arg1:string):Promise<Array<string>>;

export function ClearHistory():Promise<void>;

export function ClearMessages():Promise<void>;

export function Conference(arg1:Array<string>):Promise<void>;

export function ConfigureGlobalShortcuts():Promise<void>;

export function Contacts(arg1:string):Promise<Array<store.Contact>>;

export function ContactsPage(arg1:string,arg2:number,arg3:number):Promise<Array<store.Contact>>;

export function Conversations(arg1:string,arg2:string):Promise<Array<store.Conversation>>;

export function DeleteContact(arg1:number):Promise<void>;

export function DeleteConversation(arg1:string,arg2:string):Promise<void>;

export function DeleteDirectoryPassword():Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DeleteSavedPassword(arg1:string):Promise<void>;

export function DesktopSettings():Promise<app.DesktopSettings>;

export function Dial(arg1:string,arg2:string):Promise<void>;

export function DialFeature(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DialVoicemail(arg1:string):Promise<void>;

export function DirectoryState():Promise<directory.State>;

export function DisableConfig(arg1:string):Promise<void>;

export function DisableGlobalShortcuts():Promise<void>;

export function DiscoverDirectory(arg1:store.DirectoryConfig):Promise<Array<string>>;

export function DiscoverDirectoryServers(arg1:string):Promise<Array<string>>;

export function EnableConfig(arg1:string,arg2:string):Promise<void>;

export function EnableGlobalShortcuts():Promise<void>;

export function ExportContacts(arg1:string):Promise<void>;

export function ExportContactsCSV():Promise<string>;

export function ExportContactsVCard():Promise<string>;

export function ExportDiagnostics(arg1:boolean):Promise<void>;

export function GetConfig(arg1:string,arg2:string):Promise<config.Config>;

export function GetGlobalShortcuts():Promise<desktop.ShortcutSettings>;

export function Hangup(arg1:string):Promise<void>;

export function History():Promise<Array<store.History>>;

export function HistoryPage(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<store.History>>;

export function Hold(arg1:string,arg2:boolean):Promise<void>;

export function ImportContactFile(arg1:string,arg2:string,arg3:boolean):Promise<store.ContactImportPreview>;

export function ImportContactsCSV(arg1:string):Promise<number>;

export function ImportContactsVCard(arg1:string):Promise<number>;

export function ImportDirectory(arg1:Array<store.Contact>):Promise<number>;

export function LastDialed(arg1:string):Promise<string>;

export function LeaveConference():Promise<void>;

export function ListConfigs():Promise<Record<string, boolean>>;

export function LookupDirectory(arg1:store.DirectoryConfig):Promise<store.DirectoryResult>;

export function MapContactCSV(arg1:string,arg2:store.CSVMapping):Promise<string>;

export function MarkConversationRead(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Messages(arg1:string,arg2:string):Promise<Array<store.Message>>;

export function MessagesPage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<store.Message>>;

export function Mute(arg1:string,arg2:boolean):Promise<void>;

export function PreviewContactImport(arg1:string,arg2:string,arg3:boolean):Promise<store.ContactImportPreview>;

export function PublishStatus(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function Quit():Promise<void>;

export function Redirect(arg1:string,arg2:string):Promise<void>;

export function RefreshDirectory():Promise<void>;

export function RemoveConfig(arg1:string,arg2:boolean):Promise<void>;

export function RequestQuit():Promise<void>;

export function RestartMediaPath(arg1:string):Promise<void>;

export function RestoreDirectoryContact(arg1:number):Promise<void>;

export function RetryAudio(arg1:string):Promise<void>;

export function SaveContact(arg1:store.Contact):Promise<void>;

export function SaveDirectoryProfile(arg1:store.DirectoryProfile,arg2:string):Promise<void>;

export function SendDTMF(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAudio(arg1:media.Settings):Promise<void>;

export function SetConfig(arg1:config.Config,arg2:string,arg3:string):Promise<void>;

export function SetDND(arg1:boolean):Promise<void>;

export function SetGain(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetPreferences(arg1:app.Preferences):Promise<void>;

export function Snapshot():Promise<phone.Snapshot>;

export function StartRecording(arg1:string):Promise<void>;

export function StopRecording(arg1:string):Promise<void>;

export function TakeDialTarget():Promise<string>;

export function TestAudio(arg1:media.Settings,arg2:string):Promise<audio.TestResult>;

export function Transfer(arg1:string,arg2:string):Promise<void>;

export function UnpublishStatus(arg1:string):Promise<void>;

export function UnwatchPresence(arg1:string,arg2:string):Promise<void>;

export function WatchPresence(arg1:string,arg2:string):Promise<void>;

export function WatchVoicemail(arg1:string):Promise<void>;
