// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableConfig(arg1, arg2) {
  return window['go']['app']['App']['EnableConfig'](arg1, arg2);
}

export function GetConfig(arg1, arg2) {
  return window['go']['app']['App']['GetConfig'](arg1, arg2);
}

export function ListConfigs() {
  return window['go']['app']['App']['ListConfigs']();
}

export function RemoveConfig(arg1, arg2) {
  return window['go']['app']['App']['RemoveConfig'](arg1, arg2);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetConfig'](arg1, arg2, arg3);
}
